fix google podcasts crawler + test
mediacloud/backend pull request #752
Opened 2020-12-28 22:04 UTC by jtotoole

This test [has been failing](https://github.com/mediacloud/backend/pull/750/checks?check_run_id=1596958198) because the `data-feed="(https?://.+?)` regex no longer works on Google Podcasts show pages if you aren't logged into Google when you fetch the page, and no longer works at all on individual episodes. I tested the new regex patterns with 6 different shows + episode pages, and it works consistently across those.

2020-12-28 22:05 UTC, jtotoole commented on apps/crawler-fetcher/tests/python/test_podcast_resolve_url.py
> +        'https://podcasts.google.com/feed/aHR0cHM6Ly93d3cucmVzaWRlbnRhZHZpc29yLm5ldC94bWwvcG9kY2FzdC54bWw/episode/'
Old episode URL in this test is now dead

2021-01-25 21:14 UTC, pypt requested changes
Thanks again!

2021-01-25 21:14 UTC, pypt commented on apps/crawler-fetcher/src/python/crawler_fetcher/handlers/feed_podcast.py
> +    if re.search(r'a class="ik7nMd" jsname="w58EXe"', html, flags=re.IGNORECASE):
First of all - thanks, very nice catch! Fun trick on determining the feed's URL from episode's URL too.

My suspicion is that `class="ik7nMd"` and `jsname="w58EXe"` get autogenerated on every code change on their end, so whenever they push out a new version, that class name will get updated and this code will break.

I've checked a few feed pages real quick, and every podcast (not episode) page seems to have exactly three `<c-data>` elements, one of which has our feed URL surrounded by some cruft. Could you perhaps parse for that instead?

2021-01-26 00:19 UTC, jtotoole commented on apps/crawler-fetcher/tests/python/test_podcast_resolve_url.py
>      # Let's just kind of hope RA doesn't change their underlying feed URL
![tumblr_mek2x7Ayfg1r4ieqao1_400](https://user-images.githubusercontent.com/6501236/105782268-96f83680-5f4a-11eb-8aa6-12daa4ad0efb.gif)

2021-01-26 00:24 UTC, jtotoole commented on apps/crawler-fetcher/tests/python/test_podcast_resolve_url.py
> +    npr_feed_url = 'https://feeds.npr.org/381444908/podcast.xml'
RA seems not to be a registered publisher on Google Podcasts anymore or something, so the formatting of their page is weird; switched to NPR instead for that reason

<img width="686" alt="Screen Shot 2021-01-25 at 8 22 59 PM" src="https://user-images.githubusercontent.com/6501236/105782627-433a1d00-5f4b-11eb-8107-56b0433f8d79.png">

2021-01-27 18:42 UTC, pypt approved these changes
Looks great now, thank you again!

2021-01-27 18:42 UTC, merged

2021-01-27 18:46 UTC, pypt commented
Whoops, sorry, gotta reopen that - fails for me with:

```
   ./dev/run_test.py apps/crawler-fetcher/tests/python/test_podcast_resolve_url.py
WARNING: The MC_UNIVISION_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The MC_UNIVISION_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The MC_UNIVISION_TEST_URL variable is not set. Defaulting to a blank string.
===================================================================== test session starts ======================================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
rootdir: /opt/mediacloud/tests/python
plugins: celery-4.4.7
collected 2 items                                                                                                                                              

opt/mediacloud/tests/python/test_podcast_resolve_url.py::test_get_feed_url_from_itunes_podcasts_url WARNING mediawords.util.web.user_agent.response.response: Content-Type header (text/javascript) is not json for https://itunes.apple.com/lookup?id=129673441&entity=podcast
INFO crawler_fetcher.handlers.feed_podcast: Resolved iTunes Podcasts URL 'https://podcasts.apple.com/lt/podcast/ra-podcast/id129673441' as 'https://ra.co/xml/podcast.xml'
WARNING mediawords.util.web.user_agent.response.response: Content-Type header (text/javascript) is not json for https://itunes.apple.com/lookup?id=129673441&entity=podcast
INFO crawler_fetcher.handlers.feed_podcast: Resolved iTunes Podcasts URL 'https://PODCASTS.APPLE.COM/lt/podcast/ra-podcast/id129673441' as 'https://ra.co/xml/podcast.xml'
WARNING mediawords.util.web.user_agent.response.response: Content-Type header (text/javascript) is not json for https://itunes.apple.com/lookup?id=129673441&entity=podcast
INFO crawler_fetcher.handlers.feed_podcast: Resolved iTunes Podcasts URL 'https://itunes.apple.com/lt/podcast/ra-podcast/id129673441' as 'https://ra.co/xml/podcast.xml'
PASSED
opt/mediacloud/tests/python/test_podcast_resolve_url.py::test_get_feed_url_from_google_podcasts_url ERROR crawler_fetcher.handlers.feed_podcast: URL 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5ucHIub3JnLzM4MTQ0NDkwOC9wb2RjYXN0LnhtbA?sa=X&ved=2ahUKEwjKm6fimbjuAhWMjoQIHUrSCW0Qjs4CKAl6BAgBEH4' doesn't have 'feed' parameter.
INFO crawler_fetcher.handlers.feed_podcast: Resolved Google Podcasts URL 'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5ucHIub3JnLzM4MTQ0NDkwOC9wb2RjYXN0LnhtbA' as 'https://play.podtrac.com/npr-381444908/edge1.pod.npr.org/anon.npr-mp3/npr/fa/2021/01/20210126_fa_fapodtues_1.mp3?awCollectionId=381444908&amp;awEpisodeId=960723263&amp;orgId=1&amp;d=2886&amp;p=381444908&amp;story=960723263&amp;t=podcast&amp;e=960723263&amp;size=46081836&amp;ft=pod&amp;f=381444908'
FAILED

=========================================================================== FAILURES ===========================================================================
__________________________________________________________ test_get_feed_url_from_google_podcasts_url __________________________________________________________

    def test_get_feed_url_from_google_podcasts_url():
        # noinspection PyTypeChecker
        assert _get_feed_url_from_google_podcasts_url(None) is None
        assert _get_feed_url_from_google_podcasts_url('') == ''
        assert _get_feed_url_from_google_podcasts_url('http://www.example.com/') == 'http://www.example.com/'
        assert _get_feed_url_from_google_podcasts_url('totally not an URL') == 'totally not an URL'
    
        npr_feed_url = 'https://feeds.npr.org/381444908/podcast.xml'
    
        # Test with URL pointing to a show's homepage (not invidual episode)
    
        npr_google_show_url = (
            'https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5ucHIub3JnLzM4MTQ0NDkwOC9wb2RjYXN0LnhtbA?sa=X'
            '&ved=2ahUKEwjKm6fimbjuAhWMjoQIHUrSCW0Qjs4CKAl6BAgBEH4'
        )
    
>       assert _get_feed_url_from_google_podcasts_url(npr_google_show_url) == npr_feed_url
E       AssertionError: assert 'https://play.podtrac.com/npr-381444908/edge1.pod.npr.org/anon.npr-mp3/npr/fa/2021/01/20210126_fa_fapodtues_1.mp3?awCollectionId=381444908&amp;awEpisodeId=960723263&amp;orgId=1&amp;d=2886&amp;p=381444908&amp;story=960723263&amp;t=podcast&amp;e=960723263&amp;size=46081836&amp;ft=pod&amp;f=381444908' == 'https://feeds.npr.org/381444908/podcast.xml'
E         - https://feeds.npr.org/381444908/podcast.xml
E         + https://play.podtrac.com/npr-381444908/edge1.pod.npr.org/anon.npr-mp3/npr/fa/2021/01/20210126_fa_fapodtues_1.mp3?awCollectionId=381444908&amp;awEpisodeId=960723263&amp;orgId=1&amp;d=2886&amp;p=381444908&amp;story=960723263&amp;t=podcast&amp;e=960723263&amp;size=46081836&amp;ft=pod&amp;f=381444908

opt/mediacloud/tests/python/test_podcast_resolve_url.py:46: AssertionError
=================================================================== short test summary info ====================================================================
FAILED opt/mediacloud/tests/python/test_podcast_resolve_url.py::test_get_feed_url_from_google_podcasts_url - AssertionError: assert 'https://play.podtrac.com...
================================================================= 1 failed, 1 passed in 1.45s ==================================================================
WARNING: The MC_UNIVISION_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The MC_UNIVISION_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The MC_UNIVISION_TEST_URL variable is not set. Defaulting to a blank string.
Subprocess returned non-zero exit status 1.
Traceback (most recent call last):
  File "./dev/run_test.py", line 162, in <module>
    subprocess.check_call(command_)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/pypt/Dropbox/etc-MediaCloud/trunk/dev/run.py', '--all_apps_dir', '/home/pypt/Dropbox/etc-MediaCloud/trunk/apps', 'crawler-fetcher', '--', 'py.test', '-s', '-vv', '-p', 'no:cacheprovider', '/opt/mediacloud/tests/python/test_podcast_resolve_url.py']' returned non-zero exit status 1.
```

Reverted on `master` for now.